DEFAULT_CONFIG_PATH = "/etc/mm/cluster-spec.yaml"
DEFAULT_DATABASE = "hamdb"
RETRY_WAIT_SECONDS = 10
CLUSTER_CHECK_INTERVAL_SECONDS = 5
CLONE_COMPATIBILITY_CHECK_INTERVAL_SECONDS = 20
MASTER_FAILURE_THRESHOLD = 3
CLUSTER_STATE_FILE_PATH = "/tmp/cluster-state.yaml"
REMOTE_SOURCE_NAME = "remote_source"
